name: Gitlint

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  gitlint:
    name: Run gitlint checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run gitlint check
        run: |
          RAW_BASE_REF="${{ github.base_ref || github.event.merge_group.base_ref }}"
          BASE_REF="${RAW_BASE_REF#refs/heads/}"
          echo "Base ref: $BASE_REF"
          git fetch origin "$BASE_REF"
          uv run gitlint --commits "origin/$BASE_REF"..HEAD
